### ISSUE TITLE
Error on load when starting VSCode from VS command prompt.

### ISSUE THREAD

**Issue by Noemata** [tristanlabelle/swift-winrt#387]
As soon as I start VSCode from the VS command prompt and open the swift-winrt folder, I'm greeted with this:

![image](https://github.com/user-attachments/assets/8e4b6fc5-b358-4e43-a0a0-353c0a629ebb)

I tried this within a VM that allows me to quickly fire up a virgin dev environment and got the same result.

If I just launch VSCode and build from there, I get this:

[proc] Executing command: "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\Common7\IDE\CommonExtensions\Microsoft\CMake\CMake\bin\cmake.exe" --version
[proc] Executing command: "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\Common7\IDE\CommonExtensions\Microsoft\CMake\CMake\bin\cmake.exe" -E capabilities
[kit] Successfully loaded 10 kits from C:\Users\mario\AppData\Local\CMakeTools\cmake-tools-kits.json
[presetController] Reading and validating the presets "file D:\Swift\swift-winrt\CMakePresets.json"
[presetController] Successfully validated D:\Swift\swift-winrt\CMakePresets.json against presets schema
[presetController] Expanding presets file D:\Swift\swift-winrt\CMakePresets.json
[presetController] Successfully expanded presets file D:\Swift\swift-winrt\CMakePresets.json
[proc] The command: C:\Windows\System32\where.exe ninja exited with code: 1
[preset] Configure preset debug: No architecture specified for cl.exe, using x64 by default
[preset] Configure preset debug: No toolset architecture specified for cl.exe, using "host=x64" by default
[preset] Using developer environment from Visual Studio (instance 48fd2308, version 17.12.35506.116, installed at "C:\Program Files\Microsoft Visual Studio\2022\Enterprise")
[proc] Executing command: chcp
[preset] Ninja is not set on PATH, trying to use C:\Program Files\Microsoft Visual Studio\2022\Enterprise\Common7\IDE\CommonExtensions\Microsoft\CMake\Ninja\ninja.exe
[preset] Configure preset debug: No architecture specified for cl.exe, using x64 by default
[main] Configuring project: swift-winrt 
[proc] Executing command: "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\Common7\IDE\CommonExtensions\Microsoft\CMake\CMake\bin\cmake.exe" -DCMAKE_BUILD_TYPE=RelWithDebInfo -DCMAKE_C_COMPILER=clang-cl -SD:/Swift/swift-winrt -BD:/Swift/swift-winrt/build/debug -G Ninja
[cmake] -- The C compiler identification is Clang 19.1.3 with MSVC-like command-line
[cmake] -- The Swift compiler identification is Apple 6.1
[cmake] -- Detecting C compiler ABI info
[cmake] -- Detecting C compiler ABI info - done
[cmake] -- Check for working C compiler: C:/Users/mario/AppData/Local/Programs/Swift/Toolchains/0.0.0+Asserts/usr/bin/clang-cl.exe - skipped
[cmake] -- Detecting C compile features
[cmake] -- Detecting C compile features - done
[cmake] -- Check for working Swift compiler: C:/Users/mario/AppData/Local/Programs/Swift/Toolchains/0.0.0+Asserts/usr/bin/swiftc.exe
[cmake] -- Check for working Swift compiler: C:/Users/mario/AppData/Local/Programs/Swift/Toolchains/0.0.0+Asserts/usr/bin/swiftc.exe - works
[cmake] -- Checking if Swift compiler exhibits bug 72724...
[cmake] -- Configuring Generator as subproject...
[cmake] -- The C compiler identification is Clang 19.1.3 with MSVC-like command-line
[cmake] -- The Swift compiler identification is Apple 6.1
[cmake] -- Detecting C compiler ABI info
[cmake] -- Detecting C compiler ABI info - done
[cmake] -- Check for working C compiler: C:/Users/mario/AppData/Local/Programs/Swift/Toolchains/0.0.0+Asserts/usr/bin/clang-cl.exe - skipped
[cmake] -- Detecting C compile features
[cmake] -- Detecting C compile features - done
[cmake] -- Check for working Swift compiler: C:/Users/mario/AppData/Local/Programs/Swift/Toolchains/0.0.0+Asserts/usr/bin/swiftc.exe
[cmake] -- Check for working Swift compiler: C:/Users/mario/AppData/Local/Programs/Swift/Toolchains/0.0.0+Asserts/usr/bin/swiftc.exe - works
[cmake] -- Configuring done (9.3s)
[cmake] -- Generating done (0.1s)
[cmake] -- Build files have been written to: D:/Swift/swift-winrt/build/debug/Generator
[cmake] -- Building Generator as subproject...
[cmake] [1/13] Linking Swift static library Dependencies\swift-argument-parser\ArgumentParserToolInfo.lib
[cmake] [2/13] Linking Swift static library Dependencies\swift-collections\DequeModule.lib
[cmake] [3/13] Linking Swift static library Dependencies\swift-collections\OrderedCollections.lib
[cmake] [4/13] Linking Swift static library Dependencies\swift-collections\Collections.lib
[cmake] [5/13] Linking Swift static library Dependencies\swift-dotnetmetadata\Sources\DotNetXMLDocs\DotNetXMLDocs.lib
[cmake] [6/13] Linking Swift static library Sources\CodeWriters\CodeWriters.lib
[cmake] [7/13] Linking Swift static library Dependencies\swift-dotnetmetadata\Sources\DotNetMetadataFormat\DotNetMetadataFormat.lib
[cmake] [8/13] Linking Swift static library Dependencies\swift-argument-parser\ArgumentParser.lib
[cmake] [9/13] Linking Swift static library Dependencies\swift-dotnetmetadata\Sources\DotNetMetadata\DotNetMetadata.lib
[cmake] [10/13] Linking Swift static library Dependencies\swift-dotnetmetadata\Sources\DotNetXMLDocsFromMetadata\DotNetXMLDocsFromMetadata.lib
[cmake] [11/13] Linking Swift static library Dependencies\swift-dotnetmetadata\Sources\WindowsMetadata\WindowsMetadata.lib
[cmake] [12/13] Linking Swift static library Sources\ProjectionModel\ProjectionModel.lib
[cmake] [13/13] Linking Swift executable Sources\SwiftWinRT\SwiftWinRT.exe
[cmake]    Creating library Sources\SwiftWinRT\SwiftWinRT.lib and object Sources\SwiftWinRT\SwiftWinRT.exp

[cmake] -- Generating WinRTComponent.winmd...
[cmake] CMake Error at InteropTests/WinRTComponent/GenerateWinMD.cmake:22 (execute_process):
[cmake]   execute_process failed command indexes:
[cmake] 
[cmake]     1: "Abnormal exit with child return code: no such file or directory"
[cmake] 
[cmake] Call Stack (most recent call first):
[cmake]   InteropTests/WinRTComponent/CMakeLists.txt:19 (generate_winrtcomponent_winmd)
[cmake] 
[cmake] 
[cmake] -- Configuring incomplete, errors occurred!
[proc] The command: "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\Common7\IDE\CommonExtensions\Microsoft\CMake\CMake\bin\cmake.exe" -DCMAKE_BUILD_TYPE=RelWithDebInfo -DCMAKE_C_COMPILER=clang-cl -SD:/Swift/swift-winrt -BD:/Swift/swift-winrt/build/debug -G Ninja exited with code: 1

So it looks like I'm most of the way there.  The executable for SwiftWinRT was created.  I suspect you'll know what is causing the problem with InteropTests/WinRTComponent/CMakeLists.txt:19 (generate_winrtcomponent_winmd).  Where should the winmd file be pulled from?  I'm obviously making some stupid mistake.

**Comment by Noemata** [comment]
Made an interesting discovery.  Using amd64 as a platform choice causes the build to fail.  That turned out to be the issue on a couple of the systems I was having trouble with.  You have to specify x64!

**Comment by Noemata** [comment]
This was not obvious at all.  Very nice work, more than a little challenging for my feeble brain.

[cmake] -- Generating Swift projection for WinRTComponent...
[cmake] Loading assembly WinRTComponent.winmd...
[cmake] Loading assembly Windows.AI.MachineLearning.MachineLearningContract.winmd...
[cmake] Loading assembly Windows.AI.MachineLearning.Preview.MachineLearningPreviewContract.winmd...
[cmake] Loading assembly Windows.ApplicationModel.Activation.ActivatedEventsContract.winmd...
[cmake] Loading assembly Windows.ApplicationModel.Activation.ActivationCameraSettingsContract.winmd...
[cmake] Loading assembly Windows.ApplicationModel.Activation.ContactActivatedEventsContract.winmd...
[cmake] Loading assembly Windows.ApplicationModel.Activation.WebUISearchActivatedEventsContract.winmd...
[cmake] Loading assembly Windows.ApplicationModel.Background.BackgroundAlarmApplicationContract.winmd...
[cmake] Loading assembly Windows.ApplicationModel.Calls.Background.CallsBackgroundContract.winmd...
[cmake] Loading assembly Windows.ApplicationModel.Calls.CallsPhoneContract.winmd...
[cmake] Loading assembly Windows.ApplicationModel.Calls.CallsVoipContract.winmd...
[cmake] Loading assembly Windows.ApplicationModel.Calls.LockScreenCallContract.winmd...
[cmake] Loading assembly Windows.ApplicationModel.CommunicationBlocking.CommunicationBlockingContract.winmd...
[cmake] Loading assembly Windows.ApplicationModel.FullTrustAppContract.winmd...
[cmake] Loading assembly Windows.ApplicationModel.Preview.InkWorkspace.PreviewInkWorkspaceContract.winmd...
[cmake] Loading assembly Windows.ApplicationModel.Preview.Notes.PreviewNotesContract.winmd...
[cmake] Loading assembly Windows.ApplicationModel.Resources.Management.ResourceIndexerContract.winmd...
[cmake] Loading assembly Windows.ApplicationModel.Search.Core.SearchCoreContract.winmd...
[cmake] Loading assembly Windows.ApplicationModel.Search.SearchContract.winmd...
[cmake] Loading assembly Windows.ApplicationModel.SocialInfo.SocialInfoContract.winmd...
[cmake] Loading assembly Windows.ApplicationModel.StartupTaskContract.winmd...
[cmake] Loading assembly Windows.ApplicationModel.Wallet.WalletContract.winmd...
[cmake] Loading assembly Windows.Devices.Custom.CustomDeviceContract.winmd...
[cmake] Loading assembly Windows.Devices.DevicesLowLevelContract.winmd...
[cmake] Loading assembly Windows.Devices.Portable.PortableDeviceContract.winmd...
[cmake] Loading assembly Windows.Devices.Power.PowerGridApiContract.winmd...
[cmake] Loading assembly Windows.Devices.Printers.Extensions.ExtensionsContract.winmd...
[cmake] Loading assembly Windows.Devices.Printers.PrintersContract.winmd...
[cmake] Loading assembly Windows.Devices.Scanners.ScannerDeviceContract.winmd...
[cmake] Loading assembly Windows.Devices.SmartCards.SmartCardBackgroundTriggerContract.winmd...
[cmake] Loading assembly Windows.Devices.SmartCards.SmartCardEmulatorContract.winmd...
[cmake] Loading assembly Windows.Devices.Sms.LegacySmsApiContract.winmd...
[cmake] Loading assembly Windows.Foundation.FoundationContract.winmd...
[cmake] Loading assembly Windows.Foundation.UniversalApiContract.winmd...
[cmake] Loading assembly Windows.Gaming.Input.GamingInputPreviewContract.winmd...
[cmake] Loading assembly Windows.Gaming.Preview.GamesEnumerationContract.winmd...
[cmake] Loading assembly Windows.Gaming.UI.GameChatOverlayContract.winmd...
[cmake] Loading assembly Windows.Gaming.UI.GamingUIProviderContract.winmd...
[cmake] Loading assembly Windows.Gaming.XboxLive.StorageApiContract.winmd...
[cmake] Loading assembly Windows.Globalization.GlobalizationJapanesePhoneticAnalyzerContract.winmd...
[cmake] Loading assembly Windows.Graphics.Printing3D.Printing3DContract.winmd...
[cmake] Loading assembly Windows.Management.Deployment.Preview.DeploymentPreviewContract.winmd...
[cmake] Loading assembly Windows.Management.Deployment.SharedPackageContainerContract.winmd...
[cmake] Loading assembly Windows.Management.Update.WindowsUpdateContract.winmd...
[cmake] Loading assembly Windows.Management.Workplace.WorkplaceSettingsContract.winmd...
[cmake] Loading assembly Windows.Media.AppBroadcasting.AppBroadcastingContract.winmd...
[cmake] Loading assembly Windows.Media.AppRecording.AppRecordingContract.winmd...
[cmake] Loading assembly Windows.Media.Capture.AppBroadcastContract.winmd...
[cmake] Loading assembly Windows.Media.Capture.AppCaptureContract.winmd...
[cmake] Loading assembly Windows.Media.Capture.AppCaptureMetadataContract.winmd...
[cmake] Loading assembly Windows.Media.Capture.CameraCaptureUIContract.winmd...
[cmake] Loading assembly Windows.Media.Capture.GameBarContract.winmd...
[cmake] Loading assembly Windows.Media.Devices.CallControlContract.winmd...
[cmake] Loading assembly Windows.Media.MediaControlContract.winmd...
[cmake] Loading assembly Windows.Media.Playlists.PlaylistsContract.winmd...
[cmake] Loading assembly Windows.Media.Protection.ProtectionRenewalContract.winmd...
[cmake] Loading assembly Windows.Networking.Connectivity.WwanContract.winmd...
[cmake] Loading assembly Windows.Networking.NetworkOperators.LegacyNetworkOperatorsContract.winmd...
[cmake] Loading assembly Windows.Networking.Sockets.ControlChannelTriggerContract.winmd...
[cmake] Loading assembly Windows.Networking.XboxLive.XboxLiveSecureSocketsContract.winmd...
[cmake] Loading assembly Windows.Perception.Automation.Core.PerceptionAutomationCoreContract.winmd...
[cmake] Loading assembly Windows.Security.EnterpriseData.EnterpriseDataContract.winmd...
[cmake] Loading assembly Windows.Security.ExchangeActiveSyncProvisioning.EasContract.winmd...
[cmake] Loading assembly Windows.Security.Isolation.IsolatedWindowsEnvironmentContract.winmd...
[cmake] Loading assembly Windows.Services.Maps.GuidanceContract.winmd...
[cmake] Loading assembly Windows.Services.Maps.LocalSearchContract.winmd...
[cmake] Loading assembly Windows.Services.Store.StoreContract.winmd...
[cmake] Loading assembly Windows.Services.TargetedContent.TargetedContentContract.winmd...
[cmake] Loading assembly Windows.Storage.Provider.CloudFilesContract.winmd...
[cmake] Loading assembly Windows.System.Profile.PlatformAutomaticAppSignInContract.winmd...
[cmake] Loading assembly Windows.System.Profile.ProfileHardwareTokenContract.winmd...
[cmake] Loading assembly Windows.System.Profile.ProfileRetailInfoContract.winmd...
[cmake] Loading assembly Windows.System.Profile.ProfileSharedModeContract.winmd...
[cmake] Loading assembly Windows.System.Profile.SystemManufacturers.SystemManufacturersContract.winmd...
[cmake] Loading assembly Windows.System.SystemManagementContract.winmd...
[cmake] Loading assembly Windows.System.UserProfile.UserProfileContract.winmd...
[cmake] Loading assembly Windows.System.UserProfile.UserProfileLockScreenContract.winmd...
[cmake] Loading assembly Windows.UI.ApplicationSettings.ApplicationsSettingsContract.winmd...
[cmake] Loading assembly Windows.UI.Core.AnimationMetrics.AnimationMetricsContract.winmd...
[cmake] Loading assembly Windows.UI.Core.CoreWindowDialogsContract.winmd...
[cmake] Loading assembly Windows.UI.Shell.SecurityAppManagerContract.winmd...
[cmake] Loading assembly Windows.UI.Shell.WindowTabManagerContract.winmd...
[cmake] Loading assembly Windows.UI.UIAutomation.UIAutomationContract.winmd...
[cmake] Loading assembly Windows.UI.ViewManagement.ViewManagementViewScalingContract.winmd...
[cmake] Loading assembly Windows.UI.Xaml.Core.Direct.XamlDirectContract.winmd...
[cmake] Loading assembly Windows.UI.Xaml.Hosting.HostingContract.winmd...
[cmake] Loading assembly Windows.Web.Http.Diagnostics.HttpDiagnosticsContract.winmd...
[cmake] Gathering types from WinRTComponent...
[cmake] Gathering types from Windows.AI.MachineLearning.MachineLearningContract...
[cmake] Gathering types from Windows.AI.MachineLearning.Preview.MachineLearningPreviewContract...
[cmake] Gathering types from Windows.ApplicationModel.Activation.ActivatedEventsContract...
[cmake] Gathering types from Windows.ApplicationModel.Activation.ActivationCameraSettingsContract...
[cmake] Gathering types from Windows.ApplicationModel.Activation.ContactActivatedEventsContract...
[cmake] Gathering types from Windows.ApplicationModel.Activation.WebUISearchActivatedEventsContract...
[cmake] Gathering types from Windows.ApplicationModel.Background.BackgroundAlarmApplicationContract...
[cmake] Gathering types from Windows.ApplicationModel.Calls.Background.CallsBackgroundContract...
[cmake] Gathering types from Windows.ApplicationModel.Calls.CallsPhoneContract...
[cmake] Gathering types from Windows.ApplicationModel.Calls.CallsVoipContract...
[cmake] Gathering types from Windows.ApplicationModel.Calls.LockScreenCallContract...
[cmake] Gathering types from Windows.ApplicationModel.CommunicationBlocking.CommunicationBlockingContract...
[cmake] Gathering types from Windows.ApplicationModel.FullTrustAppContract...
[cmake] Gathering types from Windows.ApplicationModel.Preview.InkWorkspace.PreviewInkWorkspaceContract...
[cmake] Gathering types from Windows.ApplicationModel.Preview.Notes.PreviewNotesContract...
[cmake] Gathering types from Windows.ApplicationModel.Resources.Management.ResourceIndexerContract...
[cmake] Gathering types from Windows.ApplicationModel.Search.Core.SearchCoreContract...
[cmake] Gathering types from Windows.ApplicationModel.Search.SearchContract...
[cmake] Gathering types from Windows.ApplicationModel.SocialInfo.SocialInfoContract...
[cmake] Gathering types from Windows.ApplicationModel.StartupTaskContract...
[cmake] Gathering types from Windows.ApplicationModel.Wallet.WalletContract...
[cmake] Gathering types from Windows.Devices.Custom.CustomDeviceContract...
[cmake] Gathering types from Windows.Devices.DevicesLowLevelContract...
[cmake] Gathering types from Windows.Devices.Portable.PortableDeviceContract...
[cmake] Gathering types from Windows.Devices.Power.PowerGridApiContract...
[cmake] Gathering types from Windows.Devices.Printers.Extensions.ExtensionsContract...
[cmake] Gathering types from Windows.Devices.Printers.PrintersContract...
[cmake] Gathering types from Windows.Devices.Scanners.ScannerDeviceContract...
[cmake] Gathering types from Windows.Devices.SmartCards.SmartCardBackgroundTriggerContract...
[cmake] Gathering types from Windows.Devices.SmartCards.SmartCardEmulatorContract...
[cmake] Gathering types from Windows.Devices.Sms.LegacySmsApiContract...
[cmake] Gathering types from Windows.Foundation.FoundationContract...
[cmake] Gathering types from Windows.Foundation.UniversalApiContract...
[cmake] Gathering types from Windows.Gaming.Input.GamingInputPreviewContract...
[cmake] Gathering types from Windows.Gaming.Preview.GamesEnumerationContract...
[cmake] Gathering types from Windows.Gaming.UI.GameChatOverlayContract...
[cmake] Gathering types from Windows.Gaming.UI.GamingUIProviderContract...
[cmake] Gathering types from Windows.Gaming.XboxLive.StorageApiContract...
[cmake] Gathering types from Windows.Globalization.GlobalizationJapanesePhoneticAnalyzerContract...
[cmake] Gathering types from Windows.Graphics.Printing3D.Printing3DContract...
[cmake] Gathering types from Windows.Management.Deployment.Preview.DeploymentPreviewContract...
[cmake] Gathering types from Windows.Management.Deployment.SharedPackageContainerContract...
[cmake] Gathering types from Windows.Management.Update.WindowsUpdateContract...
[cmake] Gathering types from Windows.Management.Workplace.WorkplaceSettingsContract...
[cmake] Gathering types from Windows.Media.AppBroadcasting.AppBroadcastingContract...
[cmake] Gathering types from Windows.Media.AppRecording.AppRecordingContract...
[cmake] Gathering types from Windows.Media.Capture.AppBroadcastContract...
[cmake] Gathering types from Windows.Media.Capture.AppCaptureContract...
[cmake] Gathering types from Windows.Media.Capture.AppCaptureMetadataContract...
[cmake] Gathering types from Windows.Media.Capture.CameraCaptureUIContract...
[cmake] Gathering types from Windows.Media.Capture.GameBarContract...
[cmake] Gathering types from Windows.Media.Devices.CallControlContract...
[cmake] Gathering types from Windows.Media.MediaControlContract...
[cmake] Gathering types from Windows.Media.Playlists.PlaylistsContract...
[cmake] Gathering types from Windows.Media.Protection.ProtectionRenewalContract...
[cmake] Gathering types from Windows.Networking.Connectivity.WwanContract...
[cmake] Gathering types from Windows.Networking.NetworkOperators.LegacyNetworkOperatorsContract...
[cmake] Gathering types from Windows.Networking.Sockets.ControlChannelTriggerContract...
[cmake] Gathering types from Windows.Networking.XboxLive.XboxLiveSecureSocketsContract...
[cmake] Gathering types from Windows.Perception.Automation.Core.PerceptionAutomationCoreContract...
[cmake] Gathering types from Windows.Security.EnterpriseData.EnterpriseDataContract...
[cmake] Gathering types from Windows.Security.ExchangeActiveSyncProvisioning.EasContract...
[cmake] Gathering types from Windows.Security.Isolation.IsolatedWindowsEnvironmentContract...
[cmake] Gathering types from Windows.Services.Maps.GuidanceContract...
[cmake] Gathering types from Windows.Services.Maps.LocalSearchContract...
[cmake] Gathering types from Windows.Services.Store.StoreContract...
[cmake] Gathering types from Windows.Services.TargetedContent.TargetedContentContract...
[cmake] Gathering types from Windows.Storage.Provider.CloudFilesContract...
[cmake] Gathering types from Windows.System.Profile.PlatformAutomaticAppSignInContract...
[cmake] Gathering types from Windows.System.Profile.ProfileHardwareTokenContract...
[cmake] Gathering types from Windows.System.Profile.ProfileRetailInfoContract...
[cmake] Gathering types from Windows.System.Profile.ProfileSharedModeContract...
[cmake] Gathering types from Windows.System.Profile.SystemManufacturers.SystemManufacturersContract...
[cmake] Gathering types from Windows.System.SystemManagementContract...
[cmake] Gathering types from Windows.System.UserProfile.UserProfileContract...
[cmake] Gathering types from Windows.System.UserProfile.UserProfileLockScreenContract...
[cmake] Gathering types from Windows.UI.ApplicationSettings.ApplicationsSettingsContract...
[cmake] Gathering types from Windows.UI.Core.AnimationMetrics.AnimationMetricsContract...
[cmake] Gathering types from Windows.UI.Core.CoreWindowDialogsContract...
[cmake] Gathering types from Windows.UI.Shell.SecurityAppManagerContract...
[cmake] Gathering types from Windows.UI.Shell.WindowTabManagerContract...
[cmake] Gathering types from Windows.UI.UIAutomation.UIAutomationContract...
[cmake] Gathering types from Windows.UI.ViewManagement.ViewManagementViewScalingContract...
[cmake] Gathering types from Windows.UI.Xaml.Core.Direct.XamlDirectContract...
[cmake] Gathering types from Windows.UI.Xaml.Hosting.HostingContract...
[cmake] Gathering types from Windows.Web.Http.Diagnostics.HttpDiagnosticsContract...
[cmake] Generating projection for UWP...
[cmake] Generating projection for WinRTComponent...
[cmake] -- Configuring done (86.8s)
[cmake] -- Generating done (0.1s)
[cmake] -- Build files have been written to: D:/Swift/swift-winrt/build/debug

I did have to make some tweaks.  Looks like my environment is a tad ahead of yours.  Now I have to figure out how to actually use this!

**Comment by tristanlabelle** [comment]
The part it is tripping over is:

`set(MIDLRT_EXE_NATIVE "$ENV{WindowsSdkVerBinPath}$ENV{VSCMD_ARG_HOST_ARCH}\\midlrt.exe")`

Because those environment variables probably did not exist for you. However I would expect this to work if you've started VS Code from a VS developer command prompt. Could you run `set` in the VSCode terminal and check whether those two variables are set?

> Using amd64 as a platform choice causes the build to fail. That turned out to be the issue on a couple of the systems I was having trouble with. You have to specify x64!

Where are you specifying either of these?

**Comment by Noemata** [comment]
One of the issues was the platform setting.  On my AMD PCs it defaults to AMD64 when you open up a command prompt.  I had to explicitly reset it to x64.  Had me mystified for too long.  I also had to change one of the make files to point to a newer folder target.  I'm using the latest sdks.  You're quite the makefile wiz.  Took a little time to wade through the layers of make files before I could see how this comes together.  Anyhow, I'm now trying to get swift-winui-sample going.  Currently stuck on getting the nugget package working.  I'm using your powershell script to generate the nugget package in this project, but in the sample you reference a different version number among other things.  This is all very clever, by the way.

**Comment by Noemata** [comment]
Once I realized what was at issue, I opted for an alternate approach for initializing a "VS command prompt" environment.  I did this instead:

"C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvarsall.bat" x64

You can confirm the problem for yourself if you specify amd64 as the platform.  That's exactly what I did to verify why the build was failing.  There's probably a clever way of incorporating the vcvarsall batch file into your build.

Also, for the powershell side, you could do something like:

Start-Process -FilePath "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvarsall.bat" -ArgumentList "x64" -PassThru

I'm a bit rusty with this sort of thing.  Haven't touched make files in a LONG time.  I think you already have a strategy for locating Visual Studio 2022 build components.  By the way, where are you placing nuget.exe on your system so it is located by your make files?  The only version of nuget.exe that gets installed with VS is not compatible with the version of nuget.exe you use.  I had to download the version you're using, but haven't decided where it needs to sit.

**Comment by tristanlabelle** [comment]
You can use the `x64 Native Tools Command Prompt for VS 2022` shortcut from the start menu, aka `C:\Program Files\Microsoft Visual Studio\2022\Professional\VC\Auxiliary\Build\vcvars64.bat`, which should be configured as needed.

There's a way to configure the VSCode CMake Tools extension so it will set up the vs dev environment before calling CMake too.

> where are you placing nuget.exe on your system so it is located by your make files?

You can install nuget system wide using `winget install Microsoft.NuGet`

**Comment by tristanlabelle** [comment]
I added better instructions to the underlying project: https://github.com/tristanlabelle/swift-dotnetmetadata?tab=readme-ov-file#building . I'll do the same with this one later.

**Comment by Noemata** [comment]
Looks good.  You might want to provide "nuget.exe" install details, since the version in the Win SDK won't work.  Could also provide a command line shortcut reference in the form "%comspec% /k "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvars64.bat".  Lastly, you probably want a lower limit to the Win SDK used, or an indication of the version range currently known to work.

**Comment by tristanlabelle** [comment]
That other project doesn't require NuGet, but I'll include it in the instructions for this project when I get there.

I think the project will work with any reasonable Windows SDK (probably Swift on Windows has a lower limit), so I'll adjust instructions if and when someone hits an issue.

**Comment by tristanlabelle** [comment]
Updated in https://github.com/tristanlabelle/swift-winrt/pull/391

**Comment by Noemata** [comment]
I see.  Cool.
